/*
 * generated by Xtext
 */
package com.logicfishsoftware.example.xactive.domainmodel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.logicfishsoftware.example.xactive.domainmodel.ui.internal.DomainmodelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainmodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DomainmodelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DomainmodelActivator.getInstance().getInjector(DomainmodelActivator.COM_LOGICFISHSOFTWARE_EXAMPLE_XACTIVE_DOMAINMODEL_DOMAINMODEL);
	}
	
}
