/*
 * generated by Xtext
 */
package com.logicfishsoftware.example.xactive.domainmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DomainmodelUiModule extends com.logicfishsoftware.example.xactive.domainmodel.ui.AbstractDomainmodelUiModule {
	public DomainmodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
