/*
* generated by Xtext
*/
package com.logicfishsoftware.example.xactive.domainmodel.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class DomainmodelProposalProvider extends com.logicfishsoftware.example.xactive.domainmodel.ui.contentassist.AbstractDomainmodelProposalProvider {

}
